/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve el usuario autenticado. */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista leads paginados del tenant del usuario. */
        get: operations["listLeads"];
        put?: never;
        /** Crea un lead. Soporta Idempotency-Key. */
        post: operations["createLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{leadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve un lead por id. */
        get: operations["getLead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details. */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            correlationId?: string;
        };
        /** @enum {string} */
        Role: "admin" | "sales" | "support";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
        };
        /** @enum {string} */
        LeadStatus: "new" | "qualified" | "contacted" | "won" | "lost";
        Lead: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            status: components["schemas"]["LeadStatus"];
            source: string;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Payload para crear un lead. tenantId, ownerId, createdAt, updatedAt los asigna el backend. */
        LeadCreate: {
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            status: components["schemas"]["LeadStatus"];
            source: string;
        };
        LeadPage: {
            items: components["schemas"]["Lead"][];
            total: number;
            page: number;
            pageSize: number;
        };
    };
    responses: {
        /** @description Error en formato RFC 7807. */
        Problem: {
            headers: {
                "x-correlation-id": components["headers"]["CorrelationId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Identificador de correlación que enlaza la request con sus logs/spans en el backend. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    listLeads: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: components["schemas"]["LeadStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadPage"];
                };
            };
            401: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    createLead: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID generado por el cliente para deduplicar reintentos. Si se repite, el backend devuelve la misma respuesta sin crear duplicado. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Creado */
            201: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    getLead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
}
