/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 OK as long as the FastAPI process is running. Does not contact the database or any downstream dependency. Use `/readyz` for readiness checks.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when every critical dependency (database, cache) is reachable. Returns 503 otherwise so load balancers stop routing traffic to this instance.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated user
         * @description Returns the internal user row that backs the Clerk session in the `Authorization` header, plus the tenant's `default_pipeline_id` for convenience. Returns 404 if the Clerk user has no internal row yet (the Clerk webhook is responsible for provisioning it).
         */
        get: operations["get_me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List leads
         * @description Returns a paginated list of leads scoped to the caller's tenant. Filters are AND-ed; the `q` parameter performs a case-insensitive match against name, email, phone and company.
         */
        get: operations["list_leads_v1_leads_get"];
        put?: never;
        /**
         * Create lead
         * @description Creates a new lead inside the caller's tenant. Defaults to the tenant's default pipeline and that pipeline's first stage when `pipeline_id` / `stage_id` are omitted.
         */
        post: operations["create_lead_v1_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk update leads
         * @description Apply the same change to many leads: reassign owner, switch coarse status, add or remove tags. Idempotent in the sense that re-running produces the same final state.
         */
        post: operations["bulk_update_leads_v1_leads_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lead by ID */
        get: operations["get_lead_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        /** Soft-delete lead */
        delete: operations["delete_lead_v1_leads__lead_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update lead
         * @description Partial update; omitted fields stay unchanged.
         */
        patch: operations["update_lead_v1_leads__lead_id__patch"];
        trace?: never;
    };
    "/v1/leads/{lead_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List activities for a lead */
        get: operations["list_activities_v1_leads__lead_id__activities_get"];
        put?: never;
        /**
         * Add manual activity to a lead
         * @description Adds a manually-logged activity (note/call/email). System activities (stage_changed, status_changed, whatsapp_*…) are created by the API itself.
         */
        post: operations["create_activity_v1_leads__lead_id__activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move lead to another stage
         * @description Moves the lead to a stage inside its current pipeline. The transition is recorded as a `stage_changed` activity (and an additional `status_changed` activity when the coarse status flips). 4xx if the target stage belongs to another pipeline.
         */
        post: operations["move_lead_v1_leads__lead_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a soft-deleted lead
         * @description Reverses a previous soft-delete by clearing `deleted_at`. Idempotent: returns 204 even when the lead was never deleted or was already restored. 404 only when the lead does not exist at all in the tenant. An activity of type `restored` is appended to the timeline whenever a delete is actually reversed.
         */
        post: operations["restore_lead_v1_leads__lead_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}/whatsapp/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a WhatsApp template message to a lead
         * @description Sends a pre-approved template via the Meta Cloud API. The `Idempotency-Key` header is required so retries do not re-fire the outbound message; the same key + body returns the original response for 24h with status 200 (initial accept is 202). Returns 503 when WhatsApp credentials are not provisioned.
         */
        post: operations["send_whatsapp_template_v1_leads__lead_id__whatsapp_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pipelines */
        get: operations["list_pipelines_v1_pipelines_get"];
        put?: never;
        /**
         * Create pipeline
         * @description Create a new pipeline. Optionally pass `stages` to seed them in the same call; otherwise an empty pipeline is created. If `is_default` is true, the previously-default pipeline (if any) is demoted.
         */
        post: operations["create_pipeline_v1_pipelines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipelines/{pipeline_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pipeline by ID */
        get: operations["get_pipeline_v1_pipelines__pipeline_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update pipeline */
        patch: operations["update_pipeline_v1_pipelines__pipeline_id__patch"];
        trace?: never;
    };
    "/v1/pipelines/{pipeline_id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stages of a pipeline */
        get: operations["list_stages_v1_pipelines__pipeline_id__stages_get"];
        /**
         * Replace all stages of a pipeline
         * @description Replaces the pipeline's stages with the provided list. Positions are normalised to multiples of 10 in the order received. Fails if any lead still references a removed stage — migrate those leads first.
         */
        put: operations["replace_stages_v1_pipelines__pipeline_id__stages_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users in the tenant
         * @description Returns a paginated list of active users in the caller's tenant. Use to populate owner pickers and assignment dropdowns. `q` performs case-insensitive partial match against email and the composed first/last name. `role` filters by application role.
         */
        get: operations["list_users_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clerk webhook
         * @description Receives organization / user / membership lifecycle events from Clerk and keeps the internal `tenants` and `users` tables in sync. Signature is verified with svix; the request body must be the raw bytes Clerk signed. Returns 204 No Content on success, 400 on missing/invalid signature, 503 when the webhook secret is not configured on the server.
         */
        post: operations["clerk_webhook_webhooks_clerk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WhatsApp webhook verification (Meta)
         * @description Meta's subscription handshake. Returns `hub.challenge` verbatim when the verify token matches the configured `WHATSAPP_VERIFY_TOKEN`.
         */
        get: operations["whatsapp_verify_webhooks_whatsapp_get"];
        put?: never;
        /**
         * WhatsApp webhook events
         * @description Receives message + delivery-status events from Meta. The payload is verified with HMAC-SHA256 against `WHATSAPP_APP_SECRET` (header `X-Hub-Signature-256`). Tenant routing uses `phone_number_id` against `tenants.settings.whatsapp.phone_number_id`. Returns 204 on success (also on unmatched phone_number_id — Meta will retry otherwise).
         */
        post: operations["whatsapp_webhook_webhooks_whatsapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityCreate
         * @description User-created note / call / email logged manually.
         */
        ActivityCreate: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Summary */
            summary?: string | null;
            /** @description Activity kind; non-system kinds only (note, call, email). */
            type: components["schemas"]["ActivityType"];
        };
        /**
         * ActivityType
         * @description Discriminator for ``activities.type``.
         *
         *     New members must be added to the Postgres ``activity_type`` enum via an
         *     Alembic migration before they can be persisted.
         * @enum {string}
         */
        ActivityType: "note" | "call" | "email" | "whatsapp_inbound" | "whatsapp_outbound" | "stage_changed" | "owner_changed" | "status_changed" | "lead_created" | "restored" | "bulk_action" | "system";
        /** BulkActionActivityOut */
        BulkActionActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["BulkActionPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default bulk_action
             * @constant
             */
            type: "bulk_action";
        };
        /**
         * BulkActionPayload
         * @description Payload for `type: "bulk_action"` activities.
         */
        BulkActionPayload: {
            /**
             * Action
             * @description Bulk action identifier (e.g. 'delete', 'assign').
             */
            action: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** CallActivityOut */
        CallActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["CallPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default call
             * @constant
             */
            type: "call";
        };
        /**
         * CallPayload
         * @description Payload for `type: "call"` activities.
         */
        CallPayload: {
            /**
             * Duration Sec
             * @description Call duration in seconds.
             */
            duration_sec?: number | null;
            /**
             * Outcome
             * @description Free-text outcome (e.g. 'voicemail', 'no answer', 'closed').
             */
            outcome?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ComponentStatus
         * @description Status of a single dependency probed by readiness.
         */
        ComponentStatus: {
            /**
             * Detail
             * @description Optional human-readable detail (error message, etc.).
             */
            detail?: string | null;
            /**
             * Latency Ms
             * @description Probe latency in milliseconds (omitted if not measured).
             */
            latency_ms?: number | null;
            /**
             * Name
             * @description Component identifier (e.g. 'database').
             */
            name: string;
            /**
             * Status
             * @description Outcome of the probe.
             * @enum {string}
             */
            status: "ok" | "degraded" | "down" | "skipped";
        };
        /** EmailActivityOut */
        EmailActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["EmailPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default email
             * @constant
             */
            type: "email";
        };
        /**
         * EmailPayload
         * @description Payload for `type: "email"` activities.
         */
        EmailPayload: {
            /** Body */
            body?: string | null;
            /** Subject */
            subject?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Response payload for the liveness endpoint.
         */
        HealthStatus: {
            /**
             * Environment
             * @description Deployment environment.
             */
            environment: string;
            /**
             * Service
             * @description Logical service name.
             */
            service: string;
            /**
             * Status
             * @description Always 'ok' when the process is alive.
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Timestamp
             * Format: date-time
             * @description Server-side timestamp (UTC).
             */
            timestamp: string;
            /**
             * Version
             * @description Application version.
             */
            version: string;
        };
        /**
         * LeadBulkAction
         * @description Payload for ``POST /v1/leads/bulk``.
         *
         *     Set ``action`` to ``"update"`` (default) to mutate fields in-place, or
         *     ``"delete"`` to soft-delete every selected lead. When ``action=="delete"``
         *     the mutation fields (`assign_owner_id`, `set_status`, `add_tags`,
         *     `remove_tags`) are ignored. Use ``POST /v1/leads/{id}/restore`` to
         *     reverse a soft-delete.
         */
        LeadBulkAction: {
            /**
             * Action
             * @description `update` (default) applies the field mutations; `delete` soft-deletes every selected lead. Soft-deleted rows can be restored via `POST /v1/leads/{id}/restore`.
             * @default update
             */
            action: string;
            /** Add Tags */
            add_tags?: string[];
            /**
             * Assign Owner Id
             * @description If set, updates `owner_id` for every selected lead.
             */
            assign_owner_id?: string | null;
            /**
             * Ids
             * @description Lead IDs to operate on.
             */
            ids: string[];
            /** Remove Tags */
            remove_tags?: string[];
            /** @description Coarse status assigned to every selected lead. The lead also transitions to the first stage of its pipeline whose slug matches. */
            set_status?: components["schemas"]["LeadStatus"] | null;
        };
        /**
         * LeadBulkResult
         * @description Outcome of a bulk action.
         */
        LeadBulkResult: {
            /**
             * Ids
             * @description The IDs effectively updated.
             */
            ids: string[];
            /**
             * Matched
             * @description Number of leads found in the request scope.
             */
            matched: number;
            /**
             * Updated
             * @description Number of leads modified.
             */
            updated: number;
        };
        /**
         * LeadCreate
         * @description Payload accepted by ``POST /v1/leads``.
         */
        LeadCreate: {
            /** Company */
            company?: string | null;
            /** Cups */
            cups?: string | null;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            };
            /** Email */
            email?: string | null;
            /** Estimated Value Cents */
            estimated_value_cents?: number | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /**
             * Phone
             * Format: phone-e164
             * @description Phone number. Accepted shapes: strict E.164 (`+34600999111`), digits without `+` (`34600999111`), with grouping characters (spaces, dashes or parentheses), or the `00` international prefix (`0034600999111`). Server normalises to strict E.164 (`+<country><subscriber>`, 7-15 digits total). Invalid inputs return 422.
             */
            phone?: string | null;
            /**
             * Pipeline Id
             * @description Defaults to the tenant's default pipeline when omitted.
             */
            pipeline_id?: string | null;
            /** @default manual */
            source: components["schemas"]["LeadSource"];
            /** Source Ref */
            source_ref?: string | null;
            /**
             * Stage Id
             * @description Defaults to the first stage of the chosen pipeline.
             */
            stage_id?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** LeadCreatedActivityOut */
        LeadCreatedActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["LeadCreatedPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default lead_created
             * @constant
             */
            type: "lead_created";
        };
        /**
         * LeadCreatedPayload
         * @description Payload for `type: "lead_created"` activities.
         */
        LeadCreatedPayload: {
            /** Pipeline Id */
            pipeline_id?: string | null;
            /** Source */
            source?: string | null;
            /** Stage Id */
            stage_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LeadMove
         * @description Payload for ``POST /v1/leads/{id}/move``.
         */
        LeadMove: {
            /**
             * Note
             * @description Optional comment recorded as a `stage_changed` activity payload.
             */
            note?: string | null;
            /**
             * Position
             * @description Optional zero-based index inside the destination stage. When present, the lead is inserted at this position and following leads are shifted by +1. Omit (or send `null`) to append at the end of the stage — the previous behaviour. Out-of-range values are clamped to `[0, len(stage_leads)]`.
             */
            position?: number | null;
            /**
             * Stage Id
             * Format: uuid
             * @description Destination stage. Must belong to the lead's pipeline.
             */
            stage_id: string;
        };
        /**
         * LeadOut
         * @description Single-lead response.
         */
        LeadOut: {
            /** Company */
            company: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cups */
            cups: string | null;
            /** Currency */
            currency: string;
            /** Custom Fields */
            custom_fields: {
                [key: string]: unknown;
            };
            /** Email */
            email: string | null;
            /** Estimated Value Cents */
            estimated_value_cents: number | null;
            /** First Name */
            first_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Contacted At */
            last_contacted_at: string | null;
            /** Last Name */
            last_name: string | null;
            /** Owner Id */
            owner_id: string | null;
            /** Phone E164 */
            phone_e164: string | null;
            /**
             * Pipeline Id
             * Format: uuid
             */
            pipeline_id: string;
            /**
             * Position
             * @description Ordering inside the current stage. `null` means 'at the end' (legacy default). Updated by `POST /v1/leads/{id}/move` with an explicit `position`.
             */
            position?: number | null;
            source: components["schemas"]["LeadSource"];
            /** Source Ref */
            source_ref: string | null;
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            status: components["schemas"]["LeadStatus"];
            /** Tags */
            tags: string[];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LeadSortField
         * @description Permitted columns for ``GET /v1/leads?sort=`` to keep ordering safe.
         * @enum {string}
         */
        LeadSortField: "created_at" | "updated_at" | "last_contacted_at" | "status";
        /**
         * LeadSource
         * @description How the lead reached the funnel.
         * @enum {string}
         */
        LeadSource: "manual" | "whatsapp" | "web_form" | "import" | "referral" | "agent" | "other";
        /**
         * LeadStatus
         * @description Coarse lifecycle bucket; derived from the lead's current stage.
         * @enum {string}
         */
        LeadStatus: "new" | "contacted" | "qualified" | "won" | "lost";
        /**
         * LeadUpdate
         * @description PATCH payload — every field is optional.
         */
        LeadUpdate: {
            /** Company */
            company?: string | null;
            /** Cups */
            cups?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /** Email */
            email?: string | null;
            /** Estimated Value Cents */
            estimated_value_cents?: number | null;
            /** First Name */
            first_name?: string | null;
            /** Last Contacted At */
            last_contacted_at?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Owner Id */
            owner_id?: string | null;
            /**
             * Phone
             * Format: phone-e164
             * @description Phone number. Accepted shapes: strict E.164 (`+34600999111`), digits without `+` (`34600999111`), with grouping characters (spaces, dashes or parentheses), or the `00` international prefix (`0034600999111`). Server normalises to strict E.164 (`+<country><subscriber>`, 7-15 digits total). Invalid inputs return 422. Send an empty string (`""`) or JSON `null` to clear the stored phone explicitly; omit the key to leave it unchanged.
             */
            phone?: string | null;
            source?: components["schemas"]["LeadSource"] | null;
            /** Source Ref */
            source_ref?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * MeOut
         * @description ``GET /v1/auth/me`` response.
         *
         *     Extends :class:`UserOut` with the tenant's default pipeline id so the
         *     frontend can route new-lead URLs without an extra `/v1/pipelines` round
         *     trip.
         */
        MeOut: {
            /**
             * Clerk User Id
             * @description Clerk identity id (e.g. `user_2abc…`). Stable across sessions.
             */
            clerk_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Default Pipeline Id
             * @description Pipeline id flagged `is_default=true` for the tenant; null when no pipeline has been provisioned yet (pre-seed window).
             */
            default_pipeline_id?: string | null;
            /**
             * Email
             * @description Primary email reported by Clerk.
             */
            email: string;
            /** First Name */
            first_name?: string | null;
            /**
             * Id
             * Format: uuid
             * @description Internal user UUID.
             */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /**
             * Name
             * @description Composed display name (`first_name last_name`); null when both are empty.
             */
            name?: string | null;
            /** @description Application-level role within the tenant. */
            role: components["schemas"]["UserRole"];
            /**
             * Tenant Id
             * Format: uuid
             * @description Owning tenant.
             */
            tenant_id: string;
        };
        /**
         * MessageDirection
         * @enum {string}
         */
        MessageDirection: "inbound" | "outbound";
        /**
         * MessageStatus
         * @description Outbound + inbound shared lifecycle.
         * @enum {string}
         */
        MessageStatus: "received" | "accepted" | "sent" | "delivered" | "read" | "failed";
        /** NoteActivityOut */
        NoteActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["NotePayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default note
             * @constant
             */
            type: "note";
        };
        /**
         * NotePayload
         * @description Payload for `type: "note"` activities.
         */
        NotePayload: {
            /**
             * Body
             * @description Free-text note body. Optional; legacy notes may store text in `summary`.
             */
            body?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** OwnerChangedActivityOut */
        OwnerChangedActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["OwnerChangedPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default owner_changed
             * @constant
             */
            type: "owner_changed";
        };
        /**
         * OwnerChangedPayload
         * @description Payload for `type: "owner_changed"` activities.
         */
        OwnerChangedPayload: {
            /** From Owner Id */
            from_owner_id?: string | null;
            /** To Owner Id */
            to_owner_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Page[LeadOut] */
        Page_LeadOut_: {
            /**
             * Items
             * @description Items on this page. `len(items) <= limit` always. When `offset + limit > total`, `items` is truncated to the rows that still exist past `offset`.
             */
            items: components["schemas"]["LeadOut"][];
            /**
             * Limit
             * @description Maximum items returned per page.
             */
            limit: number;
            /**
             * Offset
             * @description Offset of this page in the result set.
             */
            offset: number;
            /**
             * Total
             * @description Total number of rows matching the **filtered** query (i.e. after `q`, `statuses`, `tag`, etc. are applied) — NOT the global count of rows in the table. Pagination math: `hasMore = offset + len(items) < total`.
             */
            total: number;
        };
        /** PipelineCreate */
        PipelineCreate: {
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /**
             * Stages
             * @description Stages to create alongside the pipeline. If empty the API does NOT seed defaults.
             */
            stages?: components["schemas"]["PipelineStageIn"][];
        };
        /** PipelineOut */
        PipelineOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Default */
            is_default: boolean;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Stages
             * @description Stages belonging to this pipeline, ordered by `position`. Always present; an empty list means the pipeline has no stages.
             */
            stages: components["schemas"]["PipelineStageOut"][];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PipelineStageIn */
        PipelineStageIn: {
            /**
             * Entry Criteria
             * @description Optional array of entry criteria for the stage. Each item is either a string (shorthand for a registered criterion id) or an object `{type: string, params: object}`. Consumed by Sprint 3 auto-stage agents; Sprint 2 frontend treats it as a read-only badge.
             */
            entry_criteria?: unknown[] | null;
            /**
             * Is Lost
             * @default false
             */
            is_lost: boolean;
            /**
             * Is Won
             * @default false
             */
            is_won: boolean;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Slug */
            slug?: string | null;
        };
        /** PipelineStageOut */
        PipelineStageOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Entry Criteria
             * @description Optional array of entry criteria for the stage. Each item is either a string (shorthand for a registered criterion id) or an object `{type: string, params: object}`. Consumed by Sprint 3 auto-stage agents; Sprint 2 frontend treats it as a read-only badge.
             */
            entry_criteria?: unknown[] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Lost */
            is_lost: boolean;
            /** Is Won */
            is_won: boolean;
            /** Name */
            name: string;
            /**
             * Pipeline Id
             * Format: uuid
             */
            pipeline_id: string;
            /** Position */
            position: number;
            /** Slug */
            slug: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PipelineStageReplace
         * @description Payload for ``PUT /v1/pipelines/{id}/stages`` — replaces all stages.
         */
        PipelineStageReplace: {
            /**
             * Stages
             * @description Complete stage list. Positions normalized server-side.
             */
            stages: components["schemas"]["PipelineStageIn"][];
        };
        /** PipelineUpdate */
        PipelineUpdate: {
            /** Is Default */
            is_default?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /**
         * ReadinessStatus
         * @description Response payload for the readiness endpoint.
         */
        ReadinessStatus: {
            /**
             * Checks
             * @description Per-dependency probe results.
             */
            checks: components["schemas"]["ComponentStatus"][];
            /**
             * Environment
             * @description Deployment environment.
             */
            environment: string;
            /**
             * Service
             * @description Logical service name.
             */
            service: string;
            /**
             * Status
             * @description Aggregate readiness verdict.
             * @enum {string}
             */
            status: "ready" | "degraded" | "not_ready";
            /**
             * Timestamp
             * Format: date-time
             * @description Server-side timestamp (UTC).
             */
            timestamp: string;
            /**
             * Version
             * @description Application version.
             */
            version: string;
        };
        /** RestoredActivityOut */
        RestoredActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["RestoredPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default restored
             * @constant
             */
            type: "restored";
        };
        /**
         * RestoredPayload
         * @description Payload for `type: "restored"` activities.
         */
        RestoredPayload: {
            /**
             * Restored From
             * @description The `deleted_at` timestamp the row was restored from.
             */
            restored_from?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: "asc" | "desc";
        /** StageChangedActivityOut */
        StageChangedActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["StageChangedPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default stage_changed
             * @constant
             */
            type: "stage_changed";
        };
        /**
         * StageChangedPayload
         * @description Payload for `type: "stage_changed"` activities.
         */
        StageChangedPayload: {
            /** From Stage Id */
            from_stage_id?: string | null;
            /** From Stage Name */
            from_stage_name?: string | null;
            /** Note */
            note?: string | null;
            /**
             * To Stage Id
             * Format: uuid
             * @description Destination stage id (always present).
             */
            to_stage_id: string;
            /** To Stage Name */
            to_stage_name?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** StatusChangedActivityOut */
        StatusChangedActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["StatusChangedPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default status_changed
             * @constant
             */
            type: "status_changed";
        };
        /**
         * StatusChangedPayload
         * @description Payload for `type: "status_changed"` activities.
         */
        StatusChangedPayload: {
            /** From Status */
            from_status?: string | null;
            /**
             * To Status
             * @description Resulting status (always present).
             */
            to_status: string;
        } & {
            [key: string]: unknown;
        };
        /** SystemActivityOut */
        SystemActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["SystemPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default system
             * @constant
             */
            type: "system";
        };
        /**
         * SystemPayload
         * @description Payload for `type: "system"` activities (free-form audit entries).
         */
        SystemPayload: {
            [key: string]: unknown;
        };
        /**
         * UnknownActivityOut
         * @description Backward-compat variant for activity types not in the current vocabulary.
         *
         *     The frontend should treat `type == "unknown"` as "render generic timeline
         *     entry" — the raw row payload is preserved untouched for forward inspection.
         */
        UnknownActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default unknown
             * @constant
             */
            type: "unknown";
        };
        /**
         * UserListItem
         * @description Slimmer payload returned by ``GET /v1/users``.
         */
        UserListItem: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Name
             * @description Composed display name; null when both first/last are empty.
             */
            name?: string | null;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserListPage
         * @description Paginated envelope for ``GET /v1/users``.
         */
        UserListPage: {
            /**
             * Items
             * @description Users on this page.
             */
            items: components["schemas"]["UserListItem"][];
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * Total
             * @description Total users matching the filtered query (after `q`, `role`, etc.). Same semantics as `Page.total` — filtered count, not global.
             */
            total: number;
        };
        /**
         * UserRole
         * @description Application-level role. Mapped from Clerk org_role at sync time.
         * @enum {string}
         */
        UserRole: "admin" | "sales" | "agent" | "viewer";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhatsAppInboundActivityOut */
        WhatsAppInboundActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["WhatsAppInboundPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default whatsapp_inbound
             * @constant
             */
            type: "whatsapp_inbound";
        };
        /**
         * WhatsAppInboundPayload
         * @description Payload for `type: "whatsapp_inbound"` activities.
         */
        WhatsAppInboundPayload: {
            /** Template Name */
            template_name?: string | null;
            /**
             * Text
             * @description Inbound text body, if any.
             */
            text?: string | null;
            /**
             * Wamid
             * @description WhatsApp `wamid` (provider message id).
             */
            wamid?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * WhatsAppMessageOut
         * @description Persisted WhatsApp message returned by the API.
         */
        WhatsAppMessageOut: {
            /** Body */
            body: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delivered At */
            delivered_at: string | null;
            direction: components["schemas"]["MessageDirection"];
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** From Phone E164 */
            from_phone_e164: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Lead Id */
            lead_id: string | null;
            /** Provider Message Id */
            provider_message_id: string | null;
            /** Read At */
            read_at: string | null;
            /** Sent At */
            sent_at: string | null;
            status: components["schemas"]["MessageStatus"];
            /** Template Language */
            template_language: string | null;
            /** Template Name */
            template_name: string | null;
            /** To Phone E164 */
            to_phone_e164: string;
        };
        /** WhatsAppOutboundActivityOut */
        WhatsAppOutboundActivityOut: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lead Id
             * Format: uuid
             */
            lead_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["WhatsAppOutboundPayload"];
            /** Summary */
            summary: string | null;
            /**
             * Type
             * @default whatsapp_outbound
             * @constant
             */
            type: "whatsapp_outbound";
        };
        /**
         * WhatsAppOutboundPayload
         * @description Payload for `type: "whatsapp_outbound"` activities.
         */
        WhatsAppOutboundPayload: {
            /** Template Name */
            template_name?: string | null;
            /** Text */
            text?: string | null;
            /**
             * Wamid
             * @description WhatsApp `wamid` (provider message id) of the outbound message.
             */
            wamid?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * WhatsAppTemplateComponent
         * @description Component slot inside a pre-approved template message.
         */
        WhatsAppTemplateComponent: {
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            }[];
            /**
             * Type
             * @description header | body | button | footer
             */
            type: string;
        };
        /**
         * WhatsAppTemplateSend
         * @description Payload for ``POST /v1/leads/{id}/whatsapp/send``.
         *
         *     The Meta Cloud API only accepts pre-approved templates for first-touch
         *     outbound messages, which is the only flow we support in Sprint 2.
         */
        WhatsAppTemplateSend: {
            /** Components */
            components?: components["schemas"]["WhatsAppTemplateComponent"][];
            /**
             * Language
             * @description e.g. 'es_ES', 'en_US'.
             */
            language: string;
            /** Template Name */
            template_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All probed dependencies are healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /** @description At least one critical dependency is down. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Internal user profile + tenant default pipeline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Clerk user has no internal record yet. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_leads_v1_leads_get: {
        parameters: {
            query?: {
                /** @description Filter by coarse status. */
                statuses?: components["schemas"]["LeadStatus"][] | null;
                /** @description Filter by lead source. */
                sources?: components["schemas"]["LeadSource"][] | null;
                /** @description Filter by assigned owner. */
                owner_id?: string[] | null;
                pipeline_id?: string[] | null;
                stage_id?: string[] | null;
                /** @description Match leads having ANY of these tags. */
                tag?: string[] | null;
                created_from?: string | null;
                created_to?: string | null;
                q?: string | null;
                sort?: components["schemas"]["LeadSortField"];
                direction?: components["schemas"]["SortDirection"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LeadOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_v1_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_leads_v1_leads_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadBulkAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadBulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lead_v1_leads__lead_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lead_v1_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_v1_leads__lead_id__activities_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["NoteActivityOut"] | components["schemas"]["CallActivityOut"] | components["schemas"]["EmailActivityOut"] | components["schemas"]["WhatsAppInboundActivityOut"] | components["schemas"]["WhatsAppOutboundActivityOut"] | components["schemas"]["StageChangedActivityOut"] | components["schemas"]["StatusChangedActivityOut"] | components["schemas"]["OwnerChangedActivityOut"] | components["schemas"]["LeadCreatedActivityOut"] | components["schemas"]["RestoredActivityOut"] | components["schemas"]["BulkActionActivityOut"] | components["schemas"]["SystemActivityOut"] | components["schemas"]["UnknownActivityOut"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_activity_v1_leads__lead_id__activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteActivityOut"] | components["schemas"]["CallActivityOut"] | components["schemas"]["EmailActivityOut"] | components["schemas"]["WhatsAppInboundActivityOut"] | components["schemas"]["WhatsAppOutboundActivityOut"] | components["schemas"]["StageChangedActivityOut"] | components["schemas"]["StatusChangedActivityOut"] | components["schemas"]["OwnerChangedActivityOut"] | components["schemas"]["LeadCreatedActivityOut"] | components["schemas"]["RestoredActivityOut"] | components["schemas"]["BulkActionActivityOut"] | components["schemas"]["SystemActivityOut"] | components["schemas"]["UnknownActivityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_lead_v1_leads__lead_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_lead_v1_leads__lead_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_whatsapp_template_v1_leads__lead_id__whatsapp_send_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated UUID/string scoped to this endpoint. Required: missing header returns 400. Re-sending the same key with the same body within 24h returns 200 + the original response without re-firing the send. */
                "Idempotency-Key": string;
            };
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatsAppTemplateSend"];
            };
        };
        responses: {
            /** @description Cached response. Returned when the same `Idempotency-Key` + request body is retried within the 24h TTL. Body is identical to the original 202 payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppMessageOut"];
                };
            };
            /** @description Template accepted by WhatsApp. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppMessageOut"];
                };
            };
            /** @description Validation error, lead lacks a phone number, or the `Idempotency-Key` header is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Idempotency-Key reused with a different request body. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description WhatsApp credentials not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_pipelines_v1_pipelines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineOut"][];
                };
            };
        };
    };
    create_pipeline_v1_pipelines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_v1_pipelines__pipeline_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pipeline_v1_pipelines__pipeline_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stages_v1_pipelines__pipeline_id__stages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_stages_v1_pipelines__pipeline_id__stages_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineStageReplace"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_users_get: {
        parameters: {
            query?: {
                /** @description Free-text match on email/name. */
                q?: string | null;
                /** @description Restrict to one or more application roles. */
                role?: components["schemas"]["UserRole"][] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clerk_webhook_webhooks_clerk_post: {
        parameters: {
            query?: never;
            header?: {
                "svix-id"?: string | null;
                "svix-timestamp"?: string | null;
                "svix-signature"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_verify_webhooks_whatsapp_get: {
        parameters: {
            query?: {
                "hub.mode"?: string | null;
                "hub.challenge"?: string | null;
                "hub.verify_token"?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_webhook_webhooks_whatsapp_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Hub-Signature-256"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
